version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - shared-volume:/usr/share/nginx/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - apache
      - php
      - frontend

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
    - .env
    environment:
      MYSQL_USER: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 82:80
    depends_on:
      - mysql
  
  apache:
    container_name: apache
    build: ./backend/apache
    links:
      - php
    ports:
      - "81:80"
    volumes:
      - ./backend/php/api:/usr/local/apache2/htdocs
    depends_on: 
      - "mysql"

  php:
    container_name: php
    build: ./backend/php
    ports:
      - "9000:9000"
    volumes:
      - ./backend/php/api:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    depends_on:
      - "mysql"
  
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
      - 'shared-volume:/app/build'
volumes:
  db-data:
  shared-volume:
